import { ModelMetrics, DatasetItem } from "@/types/telemetry";

export const MOCK_METRICS: ModelMetrics = {
  top1Accuracy: 0.884, // 88.4%
  top3Accuracy: 0.962, // 96.2%
  totalRunsEvaluated: 1420,
  successfulRuns: 980,
  failedRuns: 440,
  averageConfidence: 0.897,
  categoryDistribution: [
    { category: "wrong_tool", count: 148, percentage: 33.6, top1Accuracy: 0.925 },
    { category: "wrong_argument", count: 86, percentage: 19.5, top1Accuracy: 0.895 },
    { category: "bad_retrieval", count: 68, percentage: 15.5, top1Accuracy: 0.867 },
    { category: "premature_completion", count: 44, percentage: 10.0, top1Accuracy: 0.841 },
    { category: "tool_error", count: 32, percentage: 7.3, top1Accuracy: 0.968 },
    { category: "incorrect_branch", count: 28, percentage: 6.4, top1Accuracy: 0.821 },
    { category: "context_loss", count: 18, percentage: 4.1, top1Accuracy: 0.778 },
    { category: "timeout", count: 10, percentage: 2.3, top1Accuracy: 0.90 },
    { category: "repeated_action", count: 6, percentage: 1.3, top1Accuracy: 0.833 },
  ],
  heldOutEvaluation: [
    {
      dataset: "AgentBench-MultiHop-v2",
      runsCount: 350,
      accuracy: 0.871,
      f1Score: 0.892,
      meanLatencyMs: 42,
    },
    {
      dataset: "SWE-Bench-Mini-Triaged",
      runsCount: 220,
      accuracy: 0.845,
      f1Score: 0.863,
      meanLatencyMs: 68,
    },
    {
      dataset: "ToolQA-Adversarial-HeldOut",
      runsCount: 180,
      accuracy: 0.912,
      f1Score: 0.928,
      meanLatencyMs: 38,
    },
    {
      dataset: "WebArena-Navigation-v3",
      runsCount: 260,
      accuracy: 0.865,
      f1Score: 0.884,
      meanLatencyMs: 51,
    },
  ],
};

export const MOCK_DATASET_ITEMS: DatasetItem[] = [
  {
    id: "ds_001",
    task: "Find the cheapest flight from Mumbai to Bengaluru tomorrow",
    agentName: "Voyager-Travel-v2",
    failureType: "wrong_tool",
    groundTruthStep: 5,
    split: "test",
    stepsCount: 7,
    complexity: "medium",
  },
  {
    id: "ds_002",
    task: "Investigate pod CrashLoopBackOff and patch memory",
    agentName: "KubeOps-AutoTriage",
    failureType: "wrong_argument",
    groundTruthStep: 4,
    split: "val",
    stepsCount: 5,
    complexity: "high",
  },
  {
    id: "ds_003",
    task: "Verify customer refund eligibility with 30-day window",
    agentName: "SupportSync-Copilot",
    failureType: "bad_retrieval",
    groundTruthStep: 2,
    split: "train",
    stepsCount: 4,
    complexity: "low",
  },
  {
    id: "ds_004",
    task: "Apply highest valid discount coupon for $340 cart",
    agentName: "CartOptim-Shopper",
    failureType: "premature_completion",
    groundTruthStep: 3,
    split: "test",
    stepsCount: 4,
    complexity: "medium",
  },
  {
    id: "ds_005",
    task: "Summarize Q3 quarterly revenue and risk exposure",
    agentName: "FinLedger-Analyst",
    split: "train",
    stepsCount: 5,
    complexity: "high",
  },
  {
    id: "ds_006",
    task: "Execute recursive graph partition on user cluster",
    agentName: "GraphSync-Worker",
    failureType: "context_loss",
    groundTruthStep: 8,
    split: "val",
    stepsCount: 11,
    complexity: "high",
  },
  {
    id: "ds_007",
    task: "Poll Kafka topic dead letter queue and replay offsets",
    agentName: "StreamDrainer-v1",
    failureType: "repeated_action",
    groundTruthStep: 6,
    split: "test",
    stepsCount: 9,
    complexity: "medium",
  },
];
