import { AgentRun } from "@/types/telemetry";
import {
  MOCK_TRACE_SHOWCASE_FAILED,
  MOCK_TRACE_SHOWCASE_REPLAY,
  MOCK_TRACE_FINANCIAL,
  MOCK_TRACE_KUBEOPS_FAILED,
} from "./traces";

export const MOCK_RUNS: AgentRun[] = [
  {
    runId: "run_0142",
    task: "Find the cheapest flight from Mumbai to Bengaluru tomorrow",
    agentName: "Voyager-Travel-v2",
    outcome: "failed",
    durationMs: 8420,
    timestamp: "2026-10-03T16:42:10Z",
    steps: MOCK_TRACE_SHOWCASE_FAILED,
    predictedFailureStep: 5,
    diagnosisConfidence: 0.91,
    failureType: "wrong_tool",
    totalTokens: 3420,
  },
  {
    runId: "run_0142_replay",
    task: "Find the cheapest flight from Mumbai to Bengaluru tomorrow [REPLAY]",
    agentName: "Voyager-Travel-v2",
    outcome: "success",
    durationMs: 7120,
    timestamp: "2026-10-03T16:55:00Z",
    steps: MOCK_TRACE_SHOWCASE_REPLAY,
    totalTokens: 3100,
  },
  {
    runId: "run_0141",
    task: "Summarize Q3 quarterly revenue, EBITDA margins, and risk exposure for FinTech Corp",
    agentName: "FinLedger-Analyst",
    outcome: "success",
    durationMs: 5210,
    timestamp: "2026-10-03T16:30:45Z",
    steps: MOCK_TRACE_FINANCIAL,
    totalTokens: 2980,
  },
  {
    runId: "run_0140",
    task: "Investigate pod CrashLoopBackOff in payment-gateway namespace and patch replica limit",
    agentName: "KubeOps-AutoTriage",
    outcome: "failed",
    durationMs: 6850,
    timestamp: "2026-10-03T16:15:22Z",
    steps: MOCK_TRACE_KUBEOPS_FAILED,
    predictedFailureStep: 4,
    diagnosisConfidence: 0.88,
    failureType: "wrong_argument",
    totalTokens: 2150,
  },
  {
    runId: "run_0139",
    task: "Verify customer refund eligibility for Order #98214 and dispatch webhook",
    agentName: "SupportSync-Copilot",
    outcome: "failed",
    durationMs: 4920,
    timestamp: "2026-10-03T15:58:10Z",
    steps: [
      {
        stepId: 1,
        stepType: "decision",
        title: "Extract order ID & transaction timestamp",
        output: "Order #98214, purchase date: 2026-09-12, amount: $149.00",
        latencyMs: 120,
        tokenCount: 160,
        status: "success",
      },
      {
        stepId: 2,
        stepType: "retrieval",
        title: "Retrieve return policy guidelines (STALE EMBEDDINGS)",
        input: "Query: 'customer refund return window eligibility'",
        output: "Fetched refund_policy_v2023.md (Stale: specifies 14-day window instead of current 30-day window)",
        latencyMs: 380,
        tokenCount: 840,
        status: "warning",
        suspicionScore: 0.94,
        predictedFailureType: "bad_retrieval",
      },
      {
        stepId: 3,
        stepType: "decision",
        title: "Assess eligibility based on stale 14-day window",
        output: "Elapsed: 21 days. Policy limit: 14 days. Result: Ineligible.",
        latencyMs: 210,
        tokenCount: 220,
        status: "failed",
        suspicionScore: 0.72,
      },
      {
        stepId: 4,
        stepType: "final_answer",
        title: "Reject customer refund ticket",
        output: "Refund request denied because order is past the 14-day window.",
        latencyMs: 190,
        tokenCount: 210,
        status: "failed",
      },
    ],
    predictedFailureStep: 2,
    diagnosisConfidence: 0.94,
    failureType: "bad_retrieval",
    totalTokens: 1850,
  },
  {
    runId: "run_0138",
    task: "Synthesize latest findings on speculative decoding latency improvements in open weights",
    agentName: "ResearchScout-v4",
    outcome: "success",
    durationMs: 12400,
    timestamp: "2026-10-03T15:40:02Z",
    steps: [
      {
        stepId: 1,
        stepType: "retrieval",
        title: "Search arXiv CS.CL for draft preprints",
        latencyMs: 820,
        tokenCount: 1100,
        status: "success",
      },
      {
        stepId: 2,
        stepType: "model_call",
        title: "Summarize speedup ratios across draft models",
        latencyMs: 1240,
        tokenCount: 2400,
        status: "success",
      },
      {
        stepId: 3,
        stepType: "final_answer",
        title: "Compile comparative latency benchmark table",
        latencyMs: 910,
        tokenCount: 1600,
        status: "success",
      },
    ],
    totalTokens: 5100,
  },
  {
    runId: "run_0137",
    task: "Apply highest valid discount coupon for cart checkout with total $340",
    agentName: "CartOptim-Shopper",
    outcome: "failed",
    durationMs: 3840,
    timestamp: "2026-10-03T15:12:30Z",
    steps: [
      {
        stepId: 1,
        stepType: "decision",
        title: "Parse active discount coupon list from promotional banner",
        output: "Coupons available: ['SAVE10', 'FALL25', 'VIP50', 'FREESHIP']",
        latencyMs: 130,
        tokenCount: 210,
        status: "success",
      },
      {
        stepId: 2,
        stepType: "tool_call",
        title: "Test coupon code: SAVE10",
        toolName: "validate_promo_code",
        input: "{ code: 'SAVE10', cartTotal: 340 }",
        output: "{ valid: false, error: 'Expired coupon' }",
        latencyMs: 310,
        tokenCount: 150,
        status: "success",
      },
      {
        stepId: 3,
        stepType: "decision",
        title: "Halt coupon verification loop prematurely",
        input: "Evaluate remaining coupons: ['FALL25', 'VIP50', 'FREESHIP']",
        output: "Encountered 1 failure. Terminating coupon search and completing checkout without discounts.",
        latencyMs: 240,
        tokenCount: 180,
        status: "warning",
        suspicionScore: 0.86,
        predictedFailureType: "premature_completion",
      },
      {
        stepId: 4,
        stepType: "final_answer",
        title: "Submit order with zero discount applied",
        output: "No active discount applied. Checkout completed at full price $340.00.",
        latencyMs: 220,
        tokenCount: 190,
        status: "failed",
      },
    ],
    predictedFailureStep: 3,
    diagnosisConfidence: 0.86,
    failureType: "premature_completion",
    totalTokens: 1420,
  },
  {
    runId: "run_0136",
    task: "Execute zero-downtime column backfill on user_sessions_partition",
    agentName: "DbMigrate-Sentinel",
    outcome: "running",
    durationMs: 23400,
    timestamp: "2026-10-03T17:05:12Z",
    steps: [
      {
        stepId: 1,
        stepType: "decision",
        title: "Acquire advisory lock and verify read replica lag",
        latencyMs: 340,
        tokenCount: 190,
        status: "success",
      },
      {
        stepId: 2,
        stepType: "tool_call",
        title: "Stream batch chunk #124 (rows 1,240,000 - 1,250,000)",
        toolName: "postgres_chunk_writer",
        latencyMs: 890,
        tokenCount: 220,
        status: "success",
      },
    ],
    totalTokens: 1120,
  },
];
