import { TraceStep } from "@/types/telemetry";

export const MOCK_TRACE_SHOWCASE_FAILED: TraceStep[] = [
  {
    stepId: 1,
    stepType: "decision",
    title: "Parse request & extract travel constraints",
    input: "User prompt: 'Find the cheapest flight from Mumbai to Bengaluru tomorrow'",
    output: JSON.stringify(
      {
        origin: "BOM",
        originCity: "Mumbai",
        destination: "BLR",
        destinationCity: "Bengaluru",
        targetDate: "2026-10-04",
        optimizationCriteria: "price_asc",
      },
      null,
      2
    ),
    latencyMs: 142,
    tokenCount: 280,
    status: "success",
    metadata: {
      parserVersion: "v2.1",
      intentConfidence: 0.992,
    },
  },
  {
    stepId: 2,
    stepType: "model_call",
    title: "Determine execution strategy & required tools",
    input: "System instruction: Determine API schema and sequence for multi-carrier flight search.",
    output: "Selected strategy: Query passenger profile for preferred carriers, then execute live carrier query with pricing sort.",
    latencyMs: 380,
    tokenCount: 410,
    status: "success",
    metadata: {
      model: "gemini-2.5-flash",
      temperature: 0.1,
    },
  },
  {
    stepId: 3,
    stepType: "retrieval",
    title: "Retrieve passenger preferences & membership tiers",
    input: JSON.stringify({ userId: "usr_99182", query: "flight_loyalty_preferences" }, null, 2),
    output: JSON.stringify(
      {
        cabinClass: "economy",
        seatPreference: "aisle",
        directFlightsPreferred: true,
        frequentFlyerPrograms: ["IndiGo 6E Rewards", "Air India Flying Returns"],
      },
      null,
      2
    ),
    latencyMs: 210,
    tokenCount: 340,
    status: "success",
    metadata: {
      source: "vector_db://user-profiles",
      similarityScore: 0.941,
    },
  },
  {
    stepId: 4,
    stepType: "decision",
    title: "Resolve live data provider connector",
    input: "Available tool manifests: ['flight_inventory_search', 'weather_forecast_service', 'hotel_reservations', 'cab_booking']",
    output: "Selecting external service connector for city condition evaluation prior to inventory ping.",
    latencyMs: 195,
    tokenCount: 220,
    status: "success",
    metadata: {
      manifestCount: 4,
    },
  },
  {
    stepId: 5,
    stepType: "tool_call",
    title: "Execute tool call: weather_forecast_service",
    toolName: "weather_forecast_service",
    input: JSON.stringify(
      {
        city: "Mumbai",
        date: "2026-10-04",
        includeForecast: true,
      },
      null,
      2
    ),
    output: JSON.stringify(
      {
        location: "Mumbai, IN",
        date: "2026-10-04",
        tempC: 28,
        condition: "Scattered clouds",
        humidity: "74%",
        precipitationProbability: "10%",
      },
      null,
      2
    ),
    latencyMs: 680,
    tokenCount: 390,
    retryCount: 0,
    status: "warning",
    suspicionScore: 0.91,
    predictedFailureType: "wrong_tool",
    metadata: {
      endpoint: "https://api.internal.tools/weather/v1/forecast",
      statusCode: 200,
      rootCauseFlag: true,
    },
  },
  {
    stepId: 6,
    stepType: "model_call",
    title: "Process tool output payload & assess flight schedule",
    input: "Evaluate tool return payload against flight criteria (BOM -> BLR, price_asc).",
    output: "Payload contains atmospheric parameters (28°C scattered clouds) but lacks flight numbers, fares, and seat availability tables.",
    latencyMs: 490,
    tokenCount: 520,
    status: "failed",
    suspicionScore: 0.74,
    metadata: {
      contextCorruption: true,
      divergenceStep: 5,
    },
  },
  {
    stepId: 7,
    stepType: "final_answer",
    title: "Synthesize user response from contaminated state",
    input: "Generate final output to user based on execution trace.",
    output: "Tomorrow's weather in Mumbai is 28°C with scattered clouds and 74% humidity. I was unable to verify any flight tickets from Mumbai to Bengaluru due to missing inventory details in the weather feed.",
    latencyMs: 310,
    tokenCount: 380,
    status: "failed",
    suspicionScore: 0.62,
    metadata: {
      evaluationVerdict: "INCORRECT_FINAL_ANSWER",
      taskCompleted: false,
    },
  },
];

export const MOCK_TRACE_SHOWCASE_REPLAY: TraceStep[] = [
  {
    stepId: 1,
    stepType: "decision",
    title: "Parse request & extract travel constraints",
    input: "User prompt: 'Find the cheapest flight from Mumbai to Bengaluru tomorrow'",
    output: JSON.stringify(
      {
        origin: "BOM",
        originCity: "Mumbai",
        destination: "BLR",
        destinationCity: "Bengaluru",
        targetDate: "2026-10-04",
        optimizationCriteria: "price_asc",
      },
      null,
      2
    ),
    latencyMs: 142,
    tokenCount: 280,
    status: "success",
    metadata: {
      parserVersion: "v2.1",
      intentConfidence: 0.992,
      checkpointRestored: true,
    },
  },
  {
    stepId: 2,
    stepType: "model_call",
    title: "Determine execution strategy & required tools",
    input: "System instruction: Determine API schema and sequence for multi-carrier flight search.",
    output: "Selected strategy: Query passenger profile for preferred carriers, then execute live carrier query with pricing sort.",
    latencyMs: 380,
    tokenCount: 410,
    status: "success",
    metadata: {
      model: "gemini-2.5-flash",
      temperature: 0.1,
      checkpointRestored: true,
    },
  },
  {
    stepId: 3,
    stepType: "retrieval",
    title: "Retrieve passenger preferences & membership tiers",
    input: JSON.stringify({ userId: "usr_99182", query: "flight_loyalty_preferences" }, null, 2),
    output: JSON.stringify(
      {
        cabinClass: "economy",
        seatPreference: "aisle",
        directFlightsPreferred: true,
        frequentFlyerPrograms: ["IndiGo 6E Rewards", "Air India Flying Returns"],
      },
      null,
      2
    ),
    latencyMs: 210,
    tokenCount: 340,
    status: "success",
    metadata: {
      source: "vector_db://user-profiles",
      similarityScore: 0.941,
      checkpointRestored: true,
    },
  },
  {
    stepId: 4,
    stepType: "decision",
    title: "Resolve live data provider connector",
    input: "Available tool manifests: ['flight_inventory_search', 'weather_forecast_service', 'hotel_reservations', 'cab_booking']",
    output: "Route query directly to flight_inventory_search GDS provider with BOM->BLR parameters.",
    latencyMs: 180,
    tokenCount: 210,
    status: "success",
    metadata: {
      checkpointRestored: true,
    },
  },
  {
    stepId: 5,
    stepType: "tool_call",
    title: "Execute tool call: flight_inventory_search [REPLAYED]",
    toolName: "flight_inventory_search",
    input: JSON.stringify(
      {
        origin: "BOM",
        destination: "BLR",
        departureDate: "2026-10-04",
        cabinClass: "economy",
        sortBy: "price_asc",
      },
      null,
      2
    ),
    output: JSON.stringify(
      {
        resultsCount: 3,
        flights: [
          {
            flightNumber: "6E-5324",
            airline: "IndiGo",
            departure: "06:15 BOM",
            arrival: "08:05 BLR",
            duration: "1h 50m",
            fareINR: 4120,
            seatsAvailable: 7,
          },
          {
            flightNumber: "QP-1382",
            airline: "Akasa Air",
            departure: "08:40 BOM",
            arrival: "10:30 BLR",
            duration: "1h 50m",
            fareINR: 4250,
            seatsAvailable: 4,
          },
          {
            flightNumber: "AI-603",
            airline: "Air India",
            departure: "11:00 BOM",
            arrival: "12:55 BLR",
            duration: "1h 55m",
            fareINR: 5100,
            seatsAvailable: 12,
          },
        ],
      },
      null,
      2
    ),
    latencyMs: 520,
    tokenCount: 460,
    retryCount: 0,
    status: "success",
    metadata: {
      isReplayDivergencePoint: true,
      endpoint: "https://api.internal.tools/travel/v2/flights/search",
      statusCode: 200,
    },
  },
  {
    stepId: 6,
    stepType: "model_call",
    title: "Verify best flight option & format price comparison",
    input: "Evaluate flight inventory against customer preference (lowest fare, direct flight).",
    output: "Optimal flight identified: IndiGo 6E-5324 departing 06:15 BOM, arriving 08:05 BLR at ₹4,120. Second best: Akasa Air QP-1382 at ₹4,250.",
    latencyMs: 340,
    tokenCount: 390,
    status: "success",
    metadata: {
      optimalSelected: "6E-5324",
    },
  },
  {
    stepId: 7,
    stepType: "final_answer",
    title: "Deliver cheapest flight recommendation with schedule",
    input: "Deliver structured flight summary to user.",
    output: "The cheapest flight from Mumbai (BOM) to Bengaluru (BLR) tomorrow is **IndiGo 6E-5324** at **₹4,120** (Departs 06:15 AM, Arrives 08:05 AM, Direct 1h 50m). The next closest option is Akasa Air QP-1382 at ₹4,250 departing at 08:40 AM.",
    latencyMs: 260,
    tokenCount: 310,
    status: "success",
    metadata: {
      evaluationVerdict: "SUCCESS",
      taskCompleted: true,
      repaired: true,
    },
  },
];

export const MOCK_TRACE_FINANCIAL: TraceStep[] = [
  {
    stepId: 1,
    stepType: "retrieval",
    title: "Fetch SEC 10-Q filing from EDGAR corpus",
    input: JSON.stringify({ ticker: "FNTK", form: "10-Q", quarter: "Q3-2026" }, null, 2),
    output: "Retrieved 148 sections from document ID sec_edgar_fntk_2026q3.",
    latencyMs: 620,
    tokenCount: 1200,
    status: "success",
  },
  {
    stepId: 2,
    stepType: "tool_call",
    title: "Extract Consolidated Statements of Operations table",
    toolName: "table_extractor_ocr",
    input: "{ section: 'Item 1 - Financial Statements', tableIndex: 2 }",
    output: "{ revenueQ3: '$842.6M', grossMargin: '68.4%', ebitda: '$198.1M' }",
    latencyMs: 410,
    tokenCount: 420,
    status: "success",
  },
  {
    stepId: 3,
    stepType: "decision",
    title: "Calculate Year-over-Year EBITDA margin growth",
    input: "Q3 2025 EBITDA margin: 21.2%. Q3 2026 EBITDA margin: 23.5%.",
    output: "YoY expansion: +230 bps.",
    latencyMs: 180,
    tokenCount: 190,
    status: "success",
  },
  {
    stepId: 4,
    stepType: "retrieval",
    title: "Query Item 1A Risk Factors updates",
    input: "Vector search: 'regulatory changes in BNPL consumer credit limits'",
    output: "Identified CFPB regulatory guideline adherence notes in paragraph 14.",
    latencyMs: 310,
    tokenCount: 650,
    status: "success",
  },
  {
    stepId: 5,
    stepType: "final_answer",
    title: "Synthesize executive financial briefing",
    output: "FinTech Corp reported Q3 revenue of $842.6M (+18% YoY) with EBITDA of $198.1M (23.5% margin, +230 bps YoY). Primary risk exposure centers on pending CFPB BNPL credit caps.",
    latencyMs: 480,
    tokenCount: 510,
    status: "success",
  },
];

export const MOCK_TRACE_KUBEOPS_FAILED: TraceStep[] = [
  {
    stepId: 1,
    stepType: "retrieval",
    title: "Poll cluster alert manager for pod status",
    input: "alertId: 'k8s-pod-crashloop-gw-09'",
    output: "Pod payment-gateway-7b9d-4x8w in namespace 'prod-payments' failing liveness probes.",
    latencyMs: 190,
    tokenCount: 220,
    status: "success",
  },
  {
    stepId: 2,
    stepType: "model_call",
    title: "Determine remediation command sequence",
    input: "Analyze pod crash reason from telemetry events.",
    output: "Issue kubectl patch or restart deployment.",
    latencyMs: 310,
    tokenCount: 380,
    status: "success",
  },
  {
    stepId: 3,
    stepType: "retrieval",
    title: "Inspect container termination status",
    output: "exitCode: 137, reason: OOMKilled, memoryLimit: '512Mi', peakUsage: '513Mi'",
    latencyMs: 240,
    tokenCount: 310,
    status: "success",
  },
  {
    stepId: 4,
    stepType: "tool_call",
    title: "Execute kubectl command: wrong argument supplied",
    toolName: "kubectl_cli",
    input: "kubectl scale deployment payment-gateway --replicas=0 -n prod-payments",
    output: "deployment.apps/payment-gateway scaled to 0 replicas.",
    latencyMs: 450,
    tokenCount: 180,
    status: "warning",
    suspicionScore: 0.88,
    predictedFailureType: "wrong_argument",
    metadata: {
      explanation: "Agent scaled replicas to zero rather than bumping resource memory limit from 512Mi to 1Gi.",
    },
  },
  {
    stepId: 5,
    stepType: "final_answer",
    title: "Report remediation status to SRE channel",
    output: "Payment gateway deployment was scaled to 0 pods to prevent restart crash loops. Service is now experiencing total outage.",
    latencyMs: 290,
    tokenCount: 260,
    status: "failed",
    suspicionScore: 0.75,
  },
];
